# Generated by Django 4.2 on 2025-03-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_products_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Update_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
