# Generated by Django 4.2 on 2025-03-11 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_created_date_products_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='created_date2',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='updated_date2',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
